---
  apiVersion: v1
  kind: List
  items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ app_name }}
      namespace: {{ namespace }}
    spec:
      selector:
        matchLabels:
          app: {{ app_name }}
      replicas: 1
      template:
        metadata:
          labels:
            app: {{ app_name }}
            aadpodidbinding: {{ aad_pod_id_name }}
        spec:
          containers:
            - name: {{ app_name }}
              image: decontainers.azurecr.io/{{ app_name }}:{{ version }}
              ports:
                - name: http-port
                  containerPort: 80
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 200m
                requests:
                  cpu: 100m
              {%- for kvp in env or [] %}
              env:
                - name:  {{kvp.split(":")[0]}}
                  value: {{kvp.split(":")[1]}}
              {%- endfor %}
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ app_name }}
      namespace: {{ namespace }}
    spec:
      type: NodePort
      selector:
        app: {{ app_name }}
      ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: {{ app_name }}
      namespace: {{ namespace }}
      annotations:
        kubernetes.io/ingress.class: azure/application-gateway
        appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{ agw_ssl_cert_name }}
    spec:
      rules:
{%- if stage == 'prod' %}
      - host: {{ app_name }}.{{ dns_domain }}
{%- else %}
      - host: {{ app_name }}-{{ stage }}.{{ dns_domain }}
{%- endif %}
        http:
          paths:
          - backend:
              serviceName: {{ app_name }}
              servicePort: 80
            path: /
  - apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: {{ app_name }}
      namespace: {{ namespace }}
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ app_name }}
      minReplicas: 1
      maxReplicas: 10
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
